export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const SEND_MESSAGE="SEND_MESSAGE";
export const FETCH_MESSAGES="FETCH_MESSAGES";
export const LIKE_MESSAGE="LIKE_MESSAGE";
export const EDIT_MESSAGE="EDIT_MESSAGE";
export const GET_MESSAGES="GET_MESSAGES";
