export const SET_CURRENT_MESSAGE_ID = "SET_CURRENT_USER_ID";
export const DROP_CURRENT_MESSAGE_ID = "DROP_CURRENT_USER_ID";
export const FETCH_MESSAGE_DATA = "FETCH_MESSAGE_DATA";
export const SET_CURRENT_MESSAGE_DATA= "SET_CURRENT_MESSAGE_DATA";